BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  priority INT CHECK (priority BETWEEN 1 AND 10),
  done BOOLEAN DEFAULT FALSE,
  category VARCHAR(50),
  due DATE,
  created TIMESTAMP DEFAULT NOW()
);
COMMIT;